# Generated by Django 3.0.8 on 2020-09-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='icon_blurhash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
