# Generated by Django 3.0.8 on 2020-09-05 12:11

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.profile_icon_upload_path),
        ),
    ]
