# Generated by Django 3.0.8 on 2020-09-04 14:45

from django.db import migrations, models


def generate_scoped_ids(apps, schema_editor):
    Quiz = apps.get_model('quizzes', 'quiz')
    db_alias = schema_editor.connection.alias
    for quiz in Quiz.objects.using(db_alias).all():
        for i, question in enumerate(quiz.question_set.using(db_alias).all()):
            question.scoped_id = i
            question.save(using=db_alias)
        print(f'Generated scoped ids for quiz {quiz}.')


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='scoped_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(generate_scoped_ids),
    ]
