# Generated by Django 3.0.8 on 2020-09-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_question_scoped_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
