# Generated by Django 3.0.8 on 2020-12-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_contribution_contributor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['created_date']},
        ),
    ]
