# Generated by Django 3.0.8 on 2020-12-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_auto_20201221_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['-created_date']},
        ),
    ]
