# Generated by Django 3.0.8 on 2020-12-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_auto_20201221_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={'ordering': ['-created_date']},
        ),
    ]
