# Generated by Django 3.2.7 on 2021-10-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_auto_20201221_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
    ]
